---
version: "3.4"

services:

  web:
    container_name: web
    image: "ssurenr/nginx_syslog"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/rsyslog.conf:/etc/rsyslog.conf:ro

  syslog-server:
    container_name: syslog-server
    image: jumanjiman/rsyslog
    ports:
      - "514:514"
    volumes:
      - ./syslog-server/ommysql.conf:/etc/rsyslog.d/ommysql.conf:ro
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/rsyslog_tables.sql:/docker-entrypoint-initdb.d/rsyslog_tables.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: rsyslog
      MYSQL_USER: rsyslog
      MYSQL_PASSWORD: rsyslog

volumes:
  db_data:
    name: dbvolume
