############################################################
# Dockerfile to build rsyslog support to nginx containers
# Based on nginx
############################################################

FROM nginx
MAINTAINER Surendhar

RUN apt-get update
RUN apt-get install -y rsyslog
